[env:due]
platform = atmelsam
board = due
framework = arduino
build_src_filter = +<*> -<wrappers/wire/wire_wrapper_fake.cpp>

[env:native]
platform = native
build_src_filter = +<*> -<main.c> -<wrappers/wire/wire_wrapper.cpp>
test_build_src = yes
